const net = require("net");
const AWS = require("aws-sdk");
const s3 = new AWS.S3();

const client = net.createConnection({ port: 9999, host: "127.0.0.1" });
let stdin = process.openStdin();

function isJSON(str) {
    try {
        JSON.parse(str);
    } catch (err) {
        return false;
    }
    return true;
}

client.on("data", (data) => {
    if (!isJSON(String(data))) {
        process.stdout.write(data.toString());
    } else {
        let recv = JSON.parse(data.toString());
        switch (recv["Type"]) {
            case "bucket-name": {
                let bName = recv["Name"];
                s3.createBucket({ Bucket: bName }, function (err, data) { if (err) throw err; });
            }
                break;
            case "create-post": {
                let bucket = recv["Bucket"];
                let key = recv["Key"]; // generated by title and timestamp
                let content = recv["Content"];
                let bucketContent = {
                    Content: content,
                    Comment: [],
                };
                // save to s3 bucket
                let param = { Bucket: bucket, Key: key, Body: JSON.stringify(bucketContent) };
                s3.upload(param, (err, result) => {
                    if (err) throw err;
                });
            }
                break;
            case "read": {
                let bucket = recv["Bucket"];
                let contentKey = recv["Key"];
                let author = recv["Author"];
                let title = recv["Title"];
                let date = recv["Date"];
                let postMetadata = "Author\t:" + author + "\nTitle\t:" + title + "\nDate\t:" + date + "\n--";
                s3.getObject({ Bucket: bucket, Key: contentKey }, (err, data) => {
                    console.log(postMetadata);
                    // parse bucket content
                    let recvContent = JSON.parse(data.Body.toString());
                    let post = recvContent["Content"];
                    let comments = recvContent["Comment"];
                    // print post
                    console.log(post + "\n--");
                    // print comment
                    for (let comment of comments) {
                        console.log(comment["Commentator"] + ": " + comment["Comment"]);
                    }
                    process.stdout.write("% ");
                });
            }
                break;
            case "comment-post": {
                // write comments into s3 bucket
                let bucket = recv["Bucket"];
                let key = recv["Key"];
                let newComment = {
                    Commentator: recv["Commentator"],
                    Comment: recv["Comment"]
                };
                s3.getObject({ Bucket: bucket, Key: key }, (err, data) => {
                    if (err) throw err;
                    let recvContent = JSON.parse(data.Body.toString());
                    recvContent["Comment"].push(newComment);
                    // save updates to s3
                    s3.upload({ Bucket: bucket, Key: key, Body: JSON.stringify(recvContent) }, (err, result) => { if (err) throw err; });
                });
                process.stdout.write("Comment successfully.\n% ");
            }
                break;
            case "delete-post": {
                let bucket = recv["Bucket"];
                let key = recv["Key"];
                s3.deleteObject({ Bucket: bucket, Key: key }, (err, result) => {
                    if (err) throw err;
                })
                process.stdout.write("Delete successfully.\n% ")
            }
                break;
            case "update-post": {
                let bucket = recv["Bucket"];
                let key = recv["Key"];
                let content = recv["Content"];
                s3.getObject({ Bucket: bucket, Key: key }, (err, data) => {
                    if (err) throw err;
                    let recvContent = JSON.parse(data.Body.toString());
                    recvContent["Content"] = content;
                    s3.upload({ Bucket: bucket, Key: key, Body: JSON.stringify(recvContent) }, (err, result) => { if (err) throw err; });
                });
                process.stdout.write("Update successfully.\n% ");
            }
                break;
            default:
                break;
        }
    }
});

stdin.addListener("data", (input) => {
    let send = String(input).replace(/\r|\n|\t/g, " ").split(" ").filter((value, index, arr) => { if (value != "") return value });
    if (send.length > 0 && send[0] === "exit") {
        process.exit();
    } else {
        client.write(input.toString());
    }
});